name: Ubuntu 18.04 Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libopencv-dev
    - name: Build dir creation
      run: mkdir build
    - name: Cmake
      working-directory: ./build
      run: cmake -DENABLE_TESTS=ON ..
    - name: make
      working-directory: ./build
      run: make
    - name: test
      working-directory: ./build
      run: ctest -V
